docker:
  mailurl: ${MAIL_URL}
---
server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
